measure: post
filters:
- key: author
- key: created_at
  criteria:
    operator: between
    value: -3M - now
dimensions:
- key: tags
  label: Tag
- key: author
  limit: 5
order: dimension1.label
format: table
