measure: post
dimensions:
- tags
- author
chart:
  type: horizontalBar
  options:
    scales:
      xAxes:
        - stacked: true
          scaleLabel:
            display: true
            labelString: Posts
      yAxes:
        - stacked: true
          scaleLabel:
            display: true
            labelString: Author
