measure: flight
dimensions:
- carrier
chart:
  type: horizontalBar
  options:
    scales:
      xAxes:
        - scaleLabel:
            display: true
            labelString: Flights
      yAxes:
        - scaleLabel:
            display: true
            labelString: Carrier
