measure:
  key: flight
  dimensions:
  - origin_market
  - carrier
chart:
  type: horizontalBar
  options:
    scales:
      xAxes:
        - stacked: true
          scaleLabel:
            display: true
            labelString: Flights
      yAxes:
        - stacked: true
          scaleLabel:
            display: true
            labelString: Market
