measure:
  key: flight
  filters:
  - carrier
  - carrier_name
  - is_on_time
  - flight_at
  dimensions:
  - flight_at
  - carrier
chart:
  options:
    scales:
      xAxes:
        - stacked: true
      yAxes:
        - stacked: true
