series:
- measure:
    key: flight
    name: All Flights
  dimensions:
  - carrier
- measure:
    key: flight
    name: On-time Flights
  filters:
  - key: is_on_time
    criteria:
      value: true
  dimensions:
  - carrier
- measure:
    key: flight
    name: Very Delayed Flights
  filters:
  - key: is_very_delayed
    criteria:
      value: true
  dimensions:
  - carrier
