series:
- measure:
    key: flight
    name: All Flights
  filters:
  - carrier
  - flight_at
  - is_on_time
  dimensions:
  - carrier
- measure:
    key: flight
    name: On-time Flights
  filters:
  - key: carrier
  - key: flight_at
  - key: is_on_time
    criteria:
      value: true
  dimensions:
  - carrier
- measure:
    key: flight
    name: Very Delayed Flights
  filters:
  - key: carrier
  - key: flight_at
  - key: is_very_delayed
    criteria:
      value: true
  dimensions:
  - carrier
