series:
- measure: flight
  filters:
  - key: origin_market
    ui_key: market
  dimensions:
  - origin_market
- measure: airport
  filters:
  - market
  dimensions:
  - market
ui_filters:
  - market
