measures:
- key: flight
  name: All Flights
- key: flight
  name: On-time Flights
  filters:
  - key: is_on_time
    criteria:
      operator: true
- key: flight
  name: Very Delayed Flights
  filters:
  - key: is_very_delayed
    criteria:
      operator: true
dimensions:
- carrier
